# Generated by Django 2.1 on 2018-08-26 04:00

from django.db import migrations, models
import io


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorlog',
            name='door_state',
            field=models.CharField(default=io.open, max_length=10),
            preserve_default=False,
        ),
    ]
